version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx-server
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./nodejs-server
    volumes:
      - /app-docker/node_modules
      - ./nodejs-server:/app-docker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRESS_USER=postgres
      - POSTGRESS_HOST=postgres
      - POSTGRESS_DATABASE=postgres
      - POSTGRESS_PASSWORD=postgres_password
      - POSTGRESS_PORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client-react
    volumes:
      - /app-docker/node_modules
      - ./client-react:/app-docker
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker-service
    volumes:
      - /app-docker/node_modules
      - ./worker-service:/app-docker
